`timescale 1ns / 1ps
/* sdram_tb.v

 Copyright (c) 2012-2014, Stephen J. Leary
 All rights reserved.
 
 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:
     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the <organization> nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
 * DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
 
module sdram_tb;

	// Inputs
	reg 	CLK128M;
	reg 	CLK32M;
	
	reg 			reset;
    
	 // SDRAM
	wire [15:0] DRAM_DQ; // SDRAM Data bus 16 Bits
	wire [12:0] DRAM_A; // SDRAM Address bus 13 Bits
	wire [1:0]	DRAM_DQM; // SDRAM Low-byte Data Mask
	wire 			DRAM_WE_N; // SDRAM Write Enable
	wire 			DRAM_CAS_N; // SDRAM Column Address Strobe
	wire 			DRAM_RAS_N; // SDRAM Row Address Strobe
	wire 			DRAM_CS_N; // SDRAM Chip Select
	wire [1:0] 	DRAM_BA; // SDRAM Bank Address
	wire 			DRAM_CLK; // SDRAM Clock
	wire 			DRAM_CKE; // SDRAM Clock Enable
	
	reg  [31:0]		wb_data_in = 0;
	wire [31:0]		wb_data_out;
	wire				wb_ack;
	reg [23:0]	 	wb_address;
	reg	[3:0]		wb_sel = 4'b1111;
	reg	[2:0]		wb_cti = 4'b000;
	reg				wb_cyc = 1'b0;
	reg				wb_stb = 1'b0;
	reg				wb_wr = 1'b0;

localparam RASCAS_DELAY   = 3'd3;   // tRCD=20ns -> 3 cycles@128MHz
localparam BURST_LENGTH   = 3'b001; // 000=1, 001=2, 010=4, 011=8
localparam ACCESS_TYPE    = 1'b0;   // 0=sequential, 1=interleaved
localparam CAS_LATENCY    = 3'd3;   // 2/3 allowed
localparam OP_MODE        = 2'b00;  // only 00 (standard operation) allowed
localparam NO_WRITE_BURST = 1'b1;   // 0= write burst enabled, 1=only single access write
localparam WRITE_BURST = 1'b0;   // 0= write burst enabled, 1=only single access write

localparam MODE = { 3'b000, WRITE_BURST, OP_MODE, CAS_LATENCY, ACCESS_TYPE, BURST_LENGTH}; 
	
	sdram_top uut(
			
		// wishbone interface
		.wb_clk		( CLK32M		),
		.wb_stb		( wb_stb		),
		.wb_cyc		( wb_cyc		),
		.wb_we		( wb_wr			),
		.wb_ack		( wb_ack		),

		.wb_sel		( wb_sel		),
		.wb_adr		( wb_address	),
		.wb_dat_i	( wb_data_in	),
		.wb_dat_o	( wb_data_out	),
		//.wb_cti_i		( wb_cti		),
				
		// SDRAM Interface
		.sd_clk		( CLK128M		),
		.sd_rst		( reset			),
		.sd_cke		( DRAM_CKE		),

		.sd_dq   	( DRAM_DQ  		),
		.sd_addr 	( DRAM_A       ),
		.sd_dqm     ( DRAM_DQM 		),
		.sd_cs_n    ( DRAM_CS_N    ),
		.sd_ba      ( DRAM_BA  		),
		.sd_we_n    ( DRAM_WE_N    ),
		.sd_ras_n   ( DRAM_RAS_N   ),
		.sd_cas_n   ( DRAM_CAS_N  	),
		.sd_ready	( ready			)

	);
	
	mt48lc16m16a2 SDRAM(
		
		.Dq			( DRAM_DQ	), 
		.Addr			( DRAM_A		), 
		.Ba			( DRAM_BA	), 
		.Clk			( CLK128M 	), 
		.Cke			( DRAM_CKE	), 
		.Cs_n			( DRAM_CS_N	), 
		.Ras_n		( DRAM_RAS_N), 
		.Cas_n		( DRAM_CAS_N), 
		.We_n			( DRAM_WE_N	), 
		.Dqm			( DRAM_DQM	)
	);

	initial begin

	   $dumpfile("sdram.vcd");
	   $dumpvars(0, sdram_tb);
	   
	   $display ("ticks: CLK");
	   $monitor ("%g %b %b %h", $time, CLK32M, wb_wr, wb_data_out);

	   // Initialize Inputs
	   CLK128M 	= 0;
	   CLK32M 	= 0;
	   reset 	= 1;
	   
	   wb_stb 	= 1'b0;
	   wb_cyc 	= 1'b0;
	   wb_wr 	= 1'b0;
	   wb_address = 0;
		
	   #50;
	   reset = 0;

	   wait(ready);
	  
	   wait(~CLK32M);
	   wait(CLK32M);
	   wb_data_in = 32'hDEADBEEF;
	   wb_address = 0;
	   wb_sel	= 4'b1011;
	   wb_wr 	= 1'b1; 
	   wb_cti	= 3'b000;
	   wb_stb 	= 1'b1;
	   wb_cyc 	= 1'b1;
	   wait(wb_ack);
	   wait(~CLK32M);
	   wait(CLK32M);   
	   wb_wr 	= 1'b0;   
	   wb_cti	= 3'b010;
	   wb_stb 	= 1'b0;
	   wb_cyc 	= 1'b0;
	   wait(wb_ack);
	   wait(~CLK32M);
	   wait(CLK32M);  
	   wb_wr 	= 1'b0; 
	   wb_stb 	= 1'b1;
	   wb_cyc 	= 1'b1;
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   wb_address = wb_address + 2;
	   wait(~wb_ack);
	   wait(wb_ack);
	   
	   
	   #30;	
	   		
	   $writememh("bank0.hex", SDRAM.Bank0);
		//$writememh("bank1.hex", SDRAM.Bank1);
		//$writememh("bank2.hex", SDRAM.Bank2);
		//$writememh("bank3.hex", SDRAM.Bank3);
	   $finish();
	   
	end
	
	always 
	begin
	   #4; CLK128M = ~CLK128M;
	end

	always 
	begin
	   #15; CLK32M = ~CLK32M;
	end

	
endmodule

