# Windows compiled on a Linux machine with mingw

TARGET = _win32
TARGETEXTENSION = .exe



CC = /usr/bin/i586-mingw32msvc-gcc
CCOUT = -o 
COPTS = -c -O2

LD = $(CC)
LDOUT = $(CCOUT)
LDFLAGS = -lm

RM = rm -f



include make.rules
